Updated my_threshold_type.py
Updated def get_n_threshold_parameters(self) to return 2 parameters instead of 1 to prevent the following error when running example.py:

2017-02-26 00:50:42 ERROR: Error executing data specification for 0, 0, 2
Traceback (most recent call last):
…
data_specification.exceptions.DataSpecificationNoMoreException: Space unavailable to write all the elements requested by the write operation. Space available: 0; space requested: 4 for region 1.