Updated my_neuron_model.py
Updated def get_n_global_parameters(self) to return 3 parameters instead of 1 to prevent the following error when running example.py:

2017-02-26 00:50:42 ERROR: Error executing data specification for 0, 0, 2
Traceback (most recent call last):
…
data_specification.exceptions.DataSpecificationNoMoreException: Space unavailable to write all the elements requested by the write operation. Space available: 0; space requested: 4 for region 1.